package liangzs.com.tomatotodo.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import liangzs.com.tomatotodo.data.entity.Task;
import liangzs.com.tomatotodo.data.entity.TaskHistory;

import liangzs.com.tomatotodo.data.greendao.TaskDao;
import liangzs.com.tomatotodo.data.greendao.TaskHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig taskDaoConfig;
    private final DaoConfig taskHistoryDaoConfig;

    private final TaskDao taskDao;
    private final TaskHistoryDao taskHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        taskHistoryDaoConfig = daoConfigMap.get(TaskHistoryDao.class).clone();
        taskHistoryDaoConfig.initIdentityScope(type);

        taskDao = new TaskDao(taskDaoConfig, this);
        taskHistoryDao = new TaskHistoryDao(taskHistoryDaoConfig, this);

        registerDao(Task.class, taskDao);
        registerDao(TaskHistory.class, taskHistoryDao);
    }
    
    public void clear() {
        taskDaoConfig.clearIdentityScope();
        taskHistoryDaoConfig.clearIdentityScope();
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public TaskHistoryDao getTaskHistoryDao() {
        return taskHistoryDao;
    }

}
